export const SET_IS_DIALOG_OPEN = "SET_IS_DIALOG_OPEN";
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const SIGN_OUT = "SIGN_OUT";
export const SET_SELECTED_TEMP_HSK = "SET_SELECTED_TEMP_HSK";
export const SET_SELECTED_HSK = "SET_SELECTED_HSK";
export const SET_SELECTED_MULTIPLE_CHOICE_ANSWER =
  "SET_SELECTED_MULTIPLE_CHOICE_ANSWER";
